// Pre-renders coastline paths for the maps so the browser doesn't parse TopoJSON.
// Run: npx tsx scripts/build-geo.ts
import { readFileSync, writeFileSync } from "node:fs";
import { geoPath, geoClipRectangle } from "d3-geo";
import { feature } from "topojson-client";
import { MAP, MINI, makeProjection } from "../src/lib/geo";

function render(file: string, cfg: typeof MAP, precision: number) {
  const topo = JSON.parse(readFileSync(`node_modules/world-atlas/${file}`, "utf8"));
  const land = feature(topo, topo.objects.land);
  const proj = makeProjection(cfg).postclip(geoClipRectangle(-20, -20, cfg.w + 20, cfg.h + 20));
  const d = geoPath(proj)(land as never) ?? "";
  const p = 10 ** precision;
  // Clipping very large polygons can emit a ring that is just the clip frame, which floods the sea; drop it.
  const frame = `M-20,-20L${cfg.w + 20},-20L${cfg.w + 20},${cfg.h + 20}L-20,${cfg.h + 20}Z`;
  return d.split(frame).join("").replace(/-?\d+\.\d+/g, (n) => String(Math.round(parseFloat(n) * p) / p));
}

const main = render("land-50m.json", MAP, 1);
const mini = render("land-10m.json", MINI, 1);
writeFileSync(
  "src/data/landPaths.ts",
  `// Generated by scripts/build-geo.ts from world-atlas (Natural Earth). Do not edit.\nexport const LAND_MAIN = ${JSON.stringify(main)};\nexport const LAND_MINI = ${JSON.stringify(mini)};\n`,
);
console.log("main", main.length, "mini", mini.length);
